### ISSUE TITLE
Locker webView ukládání hesla

### ISSUE THREAD

**Issue by David-Kr** [Ceskasporitelna/cs-core-sdk-droid#11]
Po vyplnění a odeslání hesla v locker webview je uživatel dotázán zda chce uložit heslo.Dialog je zobrazen jen chvilku než dojde ke skrytí webview (jen blikne) po přečtení oauth code.
Nejspíš problém telefonu (Huawei, Android 5.x).
Nejspíš pomůže:
webView.getSettings().setSavePassword(false);
webView.getSettings().setSaveFormData(false);

![image1 1](https://user-images.githubusercontent.com/12296581/28970955-97aa1eae-792a-11e7-98e3-39b7e20afcd2.JPG)

**Comment by hauseja3** [comment]
@David-Kr solved in new version. Thanks for suggestions.
