### ISSUE TITLE
Úprava lockeru na možnosť migrácie v aplikácii MůjStav

### ISSUE THREAD

**Issue by kvarackova** [Ceskasporitelna/cs-core-sdk-droid#12]
Ahoj.

Na aplikácii Můj Stav (QuickCheck) máme momentálne nejakú custom implementáciu registrácie/prihlasovania/odhlasovania. Radi by sme z nej prešli na locker v1 (hlavne z dôvodu, aby sme potom mohli premigrovať na locker v2), ale bez odregistrácie. Preberali sme to s Janom Hauserom a bude treba urobiť v lockeru pár zmien, aby pôvodných klientov neodregistrovalo. Časovo čím prv tým lepšie.

**Comment by hauseja3** [comment]
Solved in version v1.3.1
